Repository kumoh42/futsal-server, pull requests merged in 2023-07, with the labels that each got.

#1 nestjs 환경 설정
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: enhancement

#2 프로젝트 세팅 : .nvmrc 파일, typeOrm 패키지 추가
  .gitignore
  .nvmrc
  README.md
  package-lock.json
  package.json
  src/app.module.ts
Labels: documentation, enhancement

#4 Kum 12 readme에 정보 추가하기
  README.md
Labels: documentation

#3 chore: add ConfigModule
  README.md
  package-lock.json
  package.json
  src/app.module.ts
  src/app.service.ts
  src/entites/xe_member.entity.ts
  src/entites/xe_reservation.entity.ts
  src/entites/xe_reservation_config.entity.ts
  src/entites/xe_reservation_cricle.entity.ts
  src/entites/xe_reservation_major.entity.ts
  src/entites/xe_reservation_member.entity.ts
  src/entites/xe_reservation_pre.entity.ts
  src/main.ts
Labels: documentation
