Repository kumoh42/futsal-server, pull requests merged in 2023-11, with the labels that each got.

#72 1107 : server for develop
  .github/workflows/dev.yml
  .gitignore
  dev.Dockerfile
Labels: documentation

#73 code clean up 작업 수행
  .eslintrc.js
  .husky/pre-commit
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/members/members.controller.ts
  src/members/members.module.ts
  src/members/members.service.ts
  src/reservation/official-reservation/official-reservation.transaction.repository.ts
  src/reservation/pre-reservation/pre-reservation.service.ts
  src/reservation/pre-reservation/pre-reservation.transaction.repository.ts
  src/reservation/reservation.controller.ts
  src/reservation/reservation.module.ts
  src/reservation/time/reservation-time.transaction.repository.ts
  src/slack/slack.controller.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
  test/app.e2e-spec.ts
  tsconfig.json
Labels: enhancement

#75 fix: Delete prepare script
  package.json
Labels: bug
