Repository kumoh42/futsal-server, pull requests merged in 2023-08, with the labels that each got.

#8 Kum 19 GitHub server 자동배포
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  serverless.yml
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/entites/xe_member.entity.ts
  src/entites/xe_reservation.entity.ts
  src/entites/xe_reservation_config.entity.ts
  src/entites/xe_reservation_cricle.entity.ts
  src/entites/xe_reservation_major.entity.ts
  src/entites/xe_reservation_member.entity.ts
  src/entites/xe_reservation_pre.entity.ts
  src/main.ts
  src/serverless.ts
  tsconfig.json
Labels: enhancement

#7 로그인 기능 구현
  README.md
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/create-user.dto.ts
  src/auth/jwt/jwt.guard.ts
  src/auth/jwt/jwt.payload.ts
  src/cache/cache.module.ts
  src/cache/cache.service.ts
  src/common/decorators/user.decorator.ts
  src/entites/xe_member.futsal.entity.ts
  src/entites/xe_reservation_pre.entity.ts
  src/main.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: enhancement

#17 Kum 51 lambda 환경 세팅
  .github/workflows/deploy.yml
  .gitignore
Labels: documentation

#18 hotfix: serverless.yaml 수정
  .github/workflows/deploy.yml
  .gitignore
Labels: bug

#21 HOTFIX: changed status code
  src/auth/auth.controller.ts
  src/auth/jwt/jwt.guard.ts
Labels: HOTFIX

#28 ADD: slack api connection
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/dto/inquiry-message.dto.ts
  src/inquiry/inquiry.controller.ts
  src/inquiry/inquiry.service.ts
  src/inquiry/slack.module.ts
  src/user/user.controller.ts
Labels: enhancement

#35 hotfix: Apply Swagger Config in Lambda & Apply Format
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/dto/inquiry-message.dto.ts
  src/auth/jwt/jwt.guard.ts
  src/config/swagger.config.ts
  src/inquiry/inquiry.controller.ts
  src/inquiry/inquiry.service.ts
  src/inquiry/slack.module.ts
  src/main.ts
  src/reservation/reservation.controller.ts
  src/reservation/reservation.service.ts
  src/serverless.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: HOTFIX

#36 Feat: Merge PR to Main branch
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/dto/inquiry-message.dto.ts
  src/auth/jwt/jwt.guard.ts
  src/common/decorators/user.decorator.ts
  src/config/swagger.config.ts
  src/main.ts
  src/reservation/reservation.controller.ts
  src/reservation/reservation.service.ts
  src/serverless.ts
  src/slack/slack.controller.ts
  src/slack/slack.module.ts
  src/slack/slack.service.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: enhancement

#37 !HOTFIX:Changed .env && slack service for cicd testing
  src/slack/slack.service.ts
Labels: HOTFIX

#41 !HOTFIX: typo
  .github/workflows/deploy.yml
Labels: HOTFIX

#38 Feat: added Delete function
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/common/dto/inquiry-message.dto.ts
  src/common/dto/reservation/month-reservation-delete.dto.ts
  src/common/dto/reservation/one-reservation-delete.dto.ts
  src/reservation/reservation-transaction.ts
  src/reservation/reservation.controller.ts
  src/reservation/reservation.module.ts
  src/reservation/reservation.service.ts
  src/slack/slack.controller.ts
  src/slack/slack.module.ts
  src/slack/slack.service.ts
Labels: enhancement

#49 Feat: 삭제 변경
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/common/decorators/user.decorator.ts
  src/common/dto/inquiry-message.dto.ts
  src/common/dto/reservation/month-reservation-delete.dto.ts
  src/common/dto/reservation/one-reservation-delete.dto.ts
  src/reservation/reservation-setting.service.ts
  src/reservation/reservation-transaction.ts
  src/reservation/reservation.controller.ts
  src/reservation/reservation.module.ts
  src/reservation/reservation.service.ts
  src/serverless.ts
  src/slack/slack.controller.ts
Labels: enhancement

#51 HOTFIX: SLACK ENV VARIABLE CHANGED
  src/slack/slack.service.ts
Labels: HOTFIX
