Repository kumoh42/futsal-server, pull requests merged in 2024-01, with the labels that each got.

#80 사전 예약 시간 설정 시 스케줄러 적용 추가
  src/reservation/reservation-scheduler.ts
  src/reservation/time/reservation-time.service.ts
Labels: enhancement

#81 HOTFIX: fixed InjectDecorator name - Reservation Pre Entity
  src/reservation/official-reservation/official-reservation.transaction.repository.ts
Labels: HOTFIX

#84 Fix: switch Pre to Main Reservaion table
  src/reservation/official-reservation/official-reservation.service.ts
  src/reservation/official-reservation/official-reservation.transaction.repository.ts
  src/reservation/pre-reservation/pre-reservation.service.ts
  src/reservation/pre-reservation/pre-reservation.transaction.repository.ts
Labels: enhancement

#82 EC2 server for Deploy
  .github/workflows/deploy.yml
  .github/workflows/dev.yml
  Dockerfile
  dev.Dockerfile
Labels: documentation

#85 Fix: 사용자 설정 시 마지막 날 검사 생략
  src/reservation/reservation-scheduler.ts
Labels: HOTFIX

#86 Fix: changed function argument
  src/reservation/reservation-scheduler.ts
Labels: enhancement
